### ISSUE TITLE
cannot unstake using solflare with pumpkin pool

### ISSUE THREAD

**Issue by skleveno** [bartenbach/pumpkins_pool#1]
I cannot unstake my solana and stressed, I have 3 separate solano states and each one is giving me an error. On android, I get the int is not subtype of type string in type cast. I then restore my wallet to my laptop and tried my browser to see if it is an ap issue and still cant unstake,, the 3 staked pools total over 4k and need this for my vet vill next week. please help. i have attached a screenshot of the errors on androidn and windows

![SolflareUnstakeError](https://github.com/user-attachments/assets/75c53931-9f3e-46df-98cf-2ec06801fc80)

**Comment by Darrenpeaker** [comment]
> I cannot unstake my solana and stressed, I have 3 separate solano states and each one is giving me an error. On android, I get the int is not subtype of type string in type cast. I then restore my wallet to my laptop and tried my browser to see if it is an ap issue and still cant unstake,, the 3 staked pools total over 4k and need this for my vet vill next week. please help. i have attached a screenshot of the errors on androidn and windows

@skleveno You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[Solana Network DApps Support Ticket Requests](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by nodesupport1** [comment]
@skleveno You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID SOL07638
Please see the link below to our dedicated support line:
[Solana Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by bartenbach** [comment]
Ignore comments from scammers - are you still having issues? I'd suggest reaching out to SolFlare for support. I can't reproduce.
